# **Music Dataset**
We start by setting up the notebook and importing relevant libraries

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt #graphing and visualizations
import os

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Loading the Data

In [2]:
music_info = pd.read_csv('Music Info.csv')
music_info.head()

,track_id,name,artist,spotify_preview_url,spotify_id,tags,genre,year,duration_ms,danceability,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,TRIOREW128F424EAF0,Mr. Brightside,The Killers,https://p.scdn.co/mp3-preview/4d26180e6961fd46...,09ZQ5TmUG8TSL56n0knqrj,"rock, alternative, indie, alternative_rock, in...",NaN,2004,222200,0.355,...,1,-4.360,1,0.0746,0.001190,0.000000,0.0971,0.240,148.114,4
1,TRRIVDJ128F429B0E8,Wonderwall,Oasis,https://p.scdn.co/mp3-preview/d012e536916c927b...,06UfBBDISthj1ZJAtX4xjj,"rock, alternative, indie, pop, alternative_roc...",NaN,2006,258613,0.409,...,2,-4.373,1,0.0336,0.000807,0.000000,0.2070,0.651,174.426,4
2,TROUVHL128F426C441,Come as You Are,Nirvana,https://p.scdn.co/mp3-preview/a1c11bb1cb231031...,0keNu0t0tqsWtExGM3nT1D,"rock, alternative, alternative_rock, 90s, grunge",RnB,1991,218920,0.508,...,4,-5.783,0,0.0400,0.000175,0.000459,0.0878,0.543,120.012,4
3,TRUEIND128F93038C4,Take Me Out,Franz Ferdinand,https://p.scdn.co/mp3-preview/399c401370438be4...,0ancVQ9wEcHVd0RrGICTE4,"rock, alternative, indie, alternative_rock, in...",NaN,2004,237026,0.279,...,9,-8.851,1,0.0371,0.000389,0.000655,0.1330,0.490,104.560,4
4,TRLNZBD128F935E4D8,Creep,Radiohead,https://p.scdn.co/mp3-preview/e7eb60e9466bc3a2...,01QoK9DA7VTeTSE3MNzp4I,"rock, alternative, indie, alternative_rock, in...",RnB,2008,238640,0.515,...,7,-9.935,1,0.0369,0.010200,0.000141,0.1290,0.104,91.841,4

In [4]:
listening_info = pd.read_csv('User Listening History.csv')
listening_info.head()

             track_id                                   user_id  playcount
0  TRIRLYL128F42539D1  b80344d063b5ccb3212f76538f3d9e43d87dca9e          1
1  TRFUPBA128F934F7E1  b80344d063b5ccb3212f76538f3d9e43d87dca9e          1
2  TRLQPQJ128F42AA94F  b80344d063b5ccb3212f76538f3d9e43d87dca9e          1
3  TRTUCUY128F92E1D24  b80344d063b5ccb3212f76538f3d9e43d87dca9e          1
4  TRHDDQG12903CB53EE  b80344d063b5ccb3212f76538f3d9e43d87dca9e          1

# Better Understanding the Data

The *music_info* dataframe contains 50683 rows, each corresponding to a unique song found on Spotify, with 21 columns of identifying and descriptory information. The first column, *track_id*, serves to uniquely label each entry.

The *listening_info* dataframe contains >9 million rows, each corresponding to a unique combination of a *track_id* column and *user_id* column, followed by the value *playcount*. This allows us to relate any indivual *user_id* with the unique *track_id* list they have listened to, or to relate a *track_id* to both unique and total listeners.

In [5]:
music_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50683 entries, 0 to 50682
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   track_id             50683 non-null  object
 1   name                 50683 non-null  object
 2   artist               50683 non-null  object
 3   spotify_preview_url  50683 non-null  object
 4   spotify_id           50683 non-null  object
 5   tags                 49556 non-null  object
 6   genre                22348 non-null  object
 7   year                 50683 non-null  int64
 8   duration_ms          50683 non-null  int64
 9   danceability         50683 non-null  float64
 10  energy               50683 non-null  float64
 11  key                  50683 non-null  int64
 12  loudness             50683 non-null  float64
 13  mode                 50683 non-null  int64
 14  speechiness          50683 non-null  float64
 15  acousticness         50683 non-null  float64
 16  instrumentalness     50683 non-null  float64
 17  liveness             50683 non-null  float64
 18  valence              50683 non-null  float64
 19  tempo                50683 non-null  float64
 20  time_signature       50683 non-null  int64
dtypes: float64(9), int64(5), object(7)
memory usage: 8.1+ MB

In [6]:
listening_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9711301 entries, 0 to 9711300
Data columns (total 3 columns):
 #   Column     Dtype
---  ------     -----
 0   track_id   object
 1   user_id    object
 2   playcount  int64
dtypes: int64(1), object(2)
memory usage: 222.3+ MB

By joining these two DataFrames, using *track_id* as our index, we can make relational analyses.

In [7]:
left = music_info.set_index('track_id')
right = listening_info.set_index('track_id')
music_listening_info = left.join(right)
music_listening_info.head()

,name,artist,spotify_preview_url,spotify_id,tags,genre,year,duration_ms,danceability,energy,...,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,user_id,playcount
track_id,,,,,,,,,,,,,,,,,,,,,
TRIOREW128F424EAF0,Mr. Brightside,The Killers,https://p.scdn.co/mp3-preview/4d26180e6961fd46...,09ZQ5TmUG8TSL56n0knqrj,"rock, alternative, indie, alternative_rock, in...",NaN,2004,222200,0.355,0.918,...,1,0.0746,0.00119,0.0,0.0971,0.24,148.114,4,e95303796148a664af00f0e25059e38ab1823b30,1.0
TRIOREW128F424EAF0,Mr. Brightside,The Killers,https://p.scdn.co/mp3-preview/4d26180e6961fd46...,09ZQ5TmUG8TSL56n0knqrj,"rock, alternative, indie, alternative_rock, in...",NaN,2004,222200,0.355,0.918,...,1,0.0746,0.00119,0.0,0.0971,0.24,148.114,4,d7a8dcae75b104184e9e243bd7d6f8c79567f286,1.0
TRIOREW128F424EAF0,Mr. Brightside,The Killers,https://p.scdn.co/mp3-preview/4d26180e6961fd46...,09ZQ5TmUG8TSL56n0knqrj,"rock, alternative, indie, alternative_rock, in...",NaN,2004,222200,0.355,0.918,...,1,0.0746,0.00119,0.0,0.0971,0.24,148.114,4,c097ce6d176770f976b7fc98e8bcb0421b83c3b9,1.0
TRIOREW128F424EAF0,Mr. Brightside,The Killers,https://p.scdn.co/mp3-preview/4d26180e6961fd46...,09ZQ5TmUG8TSL56n0knqrj,"rock, alternative, indie, alternative_rock, in...",NaN,2004,222200,0.355,0.918,...,1,0.0746,0.00119,0.0,0.0971,0.24,148.114,4,1c9fcbf32a26843605b2a0daf1beb42d52924903,1.0
TRIOREW128F424EAF0,Mr. Brightside,The Killers,https://p.scdn.co/mp3-preview/4d26180e6961fd46...,09ZQ5TmUG8TSL56n0knqrj,"rock, alternative, indie, alternative_rock, in...",NaN,2004,222200,0.355,0.918,...,1,0.0746,0.00119,0.0,0.0971,0.24,148.114,4,37bb354237cf3a83cfe0d71d89b97a1d68e7d082,1.0

In [8]:
music_listening_info.describe()

,year,duration_ms,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,playcount
count,9.731525e+06,9.731525e+06,9.731525e+06,9.731525e+06,9.731525e+06,9.731525e+06,9.731525e+06,9.731525e+06,9.731525e+06,9.731525e+06,9.731525e+06,9.731525e+06,9.731525e+06,9.731525e+06,9.711301e+06
mean,2.004844e+03,2.459092e+05,5.285993e-01,6.780963e-01,5.351479e+00,-7.826373e+00,6.474120e-01,7.137277e-02,2.206735e-01,1.680002e-01,2.048089e-01,4.658126e-01,1.234278e+02,3.913521e+00,2.630946e+00
std,7.024753e+00,9.021652e+04,1.708397e-01,2.363259e-01,3.556048e+00,3.953471e+00,4.777758e-01,7.312577e-02,2.971796e-01,2.993514e-01,1.686713e-01,2.508951e-01,2.907769e+01,3.602241e-01,5.706324e+00
min,1.900000e+03,1.439000e+03,0.000000e+00,0.000000e+00,0.000000e+00,-6.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
25%,2.002000e+03,1.979260e+05,4.130000e-01,5.230000e-01,2.000000e+00,-9.633000e+00,0.000000e+00,3.350000e-02,4.230000e-03,3.830000e-06,9.750000e-02,2.610000e-01,1.008950e+02,4.000000e+00,1.000000e+00
50%,2.007000e+03,2.335730e+05,5.320000e-01,7.250000e-01,5.000000e+00,-6.919000e+00,1.000000e+00,4.440000e-02,6.110000e-02,1.140000e-03,1.330000e-01,4.420000e-01,1.218570e+02,4.000000e+00,1.000000e+00
75%,2.009000e+03,2.750920e+05,6.480000e-01,8.810000e-01,9.000000e+00,-5.089000e+00,1.000000e+00,7.450000e-02,3.430000e-01,1.560000e-01,2.760000e-01,6.710000e-01,1.420090e+02,4.000000e+00,2.000000e+00
max,2.022000e+03,3.816373e+06,9.860000e-01,1.000000e+00,1.100000e+01,3.642000e+00,1.000000e+00,9.540000e-01,9.960000e-01,9.990000e-01,9.990000e-01,9.930000e-01,2.388950e+02,5.000000e+00,2.948000e+03

# Interesting Ways to Search:

1. Searching by Artist

In [9]:
def get_discography(artist_name):
    discography = music_info.loc[music_info.artist == artist_name]
    return discography

search = get_discography('Radiohead')
search.head()

,track_id,name,artist,spotify_preview_url,spotify_id,tags,genre,year,duration_ms,danceability,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
4,TRLNZBD128F935E4D8,Creep,Radiohead,https://p.scdn.co/mp3-preview/e7eb60e9466bc3a2...,01QoK9DA7VTeTSE3MNzp4I,"rock, alternative, indie, alternative_rock, in...",RnB,2008,238640,0.515,...,7,-9.935,1,0.0369,0.0102,0.000141,0.1290,0.104,91.841,4
7,TRXOGZT128F424AD74,Karma Police,Radiohead,https://p.scdn.co/mp3-preview/5a09f5390e2862af...,01puceOqImrzSfKDAcd1Ia,"rock, alternative, indie, alternative_rock, in...",NaN,1996,264066,0.360,...,7,-9.129,1,0.0260,0.0626,0.000092,0.1720,0.317,74.807,4
25,TRIQWYH128F1486062,Paranoid Android,Radiohead,https://p.scdn.co/mp3-preview/d68bd7fa4f0bd86e...,0bomiLGPTUNyk3mV19pbwN,"rock, electronic, alternative, indie, alternat...",Jazz,2012,384933,0.232,...,5,-6.863,1,0.0573,0.0523,0.006060,0.1180,0.299,81.849,4
27,TRAGABG12903CEC68B,No Surprises,Radiohead,https://p.scdn.co/mp3-preview/de1369604de29117...,0ijMYjXk5iRZp2VsiC8MC8,"rock, alternative, indie, alternative_rock, in...",NaN,2008,229120,0.255,...,5,-10.654,1,0.0278,0.0577,0.003610,0.1130,0.118,76.426,4
72,TRCUKNC12903CA03A6,High and Dry,Radiohead,https://p.scdn.co/mp3-preview/7cc3982631523940...,0LNkoLBBuDYHc5OKY2bOvx,"rock, alternative, indie, alternative_rock, in...",NaN,2008,257480,0.418,...,4,-11.782,1,0.0257,0.0718,0.017700,0.0896,0.352,87.773,4

2. Searching by tags

In [10]:
def get_tags(tags):
    search = music_info.loc[music_info.tags.isin(tags)]
    #search = music_info.tags.str.contains(tags)
    return search

search = get_tags(['electronic', 'alternative'])
search.head()

,track_id,name,artist,spotify_preview_url,spotify_id,tags,genre,year,duration_ms,danceability,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
2698,TRAHYDH128F9325200,Piranha,The Prodigy,https://p.scdn.co/mp3-preview/9328f98175443d90...,1ySd6O5ANnwBusrZdatnLw,electronic,Rock,2009,246893,0.504,...,4,-4.525,1,0.1790,0.001350,0.754000,0.1360,0.548,165.027,4
2949,TRUKSKS128F4276237,I Can't Stop,Flux Pavilion,https://p.scdn.co/mp3-preview/1b5083582ac776ea...,03EuhmMsEHVFI9ytainStU,electronic,NaN,2010,303911,0.513,...,0,-7.202,0,0.0304,0.000672,0.248000,0.4090,0.205,139.932,4
3049,TRMNRHK12903CE5DBF,Woo Boost,Rusko,https://p.scdn.co/mp3-preview/a02810636d17dea4...,0AbnjOe5u8SfV4NbFyDNth,electronic,Electronic,2012,249480,0.660,...,11,-4.127,0,0.1150,0.000707,0.236000,0.1160,0.643,139.855,4
3129,TRXQQHB12903CE17D6,Wildfire,SBTRKT,https://p.scdn.co/mp3-preview/42582431e42f8dba...,17gLsEfiJa9IK944UFgHMR,electronic,NaN,2011,201093,0.867,...,5,-9.646,0,0.4220,0.023200,0.000402,0.0869,0.338,139.740,4
3237,TRXICZI128F1461F1B,Guilt,Nero,https://p.scdn.co/mp3-preview/dcab079c42cc03fe...,0VSdYNTKyZZZRYSHDVb4YQ,electronic,Electronic,2011,284120,0.255,...,5,-4.520,0,0.0702,0.006690,0.000001,0.1440,0.154,139.745,4

3. Searching by track_id

In [11]:
def get_song_info(id):
    artist = music_info.loc[music_info.track_id == id].artist
    name = music_info.loc[music_info.track_id == id].name
    info = pd.merge(artist, name, right_index=True, left_index=True)
    return info

track_id = 'TRLNZBD128F935E4D8'
get_song_info(track_id)

      artist   name
4  Radiohead  Creep

# Looking at Trends:

As one of the most basic and straightforward relationships between the two databases, let's first look at the most popular tracks in the database according to user listening history.

**Top Ten Tracks by Listen History**

The *count* lists the number of *user_id* entries associated with each *track_id* (i.e. number of unique listeners). The *sum* lists the summed total playcount of each track.

In [12]:
track_id_playcount = listening_info.groupby('track_id').playcount.agg(['count', 'sum'])
top_ten_id = track_id_playcount.nlargest(10, 'sum')
#top_ten_tracks = top_ten_id.apply(lambda n : get_song_info(n))
print(top_ten_id)

                    count     sum
track_id
TRONYHY128F92C9D11  80656  527893
TRUFTBY128F93450B8  39529  111615
TRZNAHL128F9327D5A  24592  111596
TRCPXID128F92D5D3C  30057   91461
TRPGPDK12903CCC651  27276   91448
TRXWAZC128F9314B3E  30873   87745
TROMKCG128F9320C09  28735   87050
TRPFYYL128F92F7144  28412   85079
TRGCHLH12903CB7352  29708   78443
TRAALAH128E078234A  26689   76893